# DATA_DIR = "./input/plates/"
# DATA_DIR = "./input/real-plates/"
DATA_DIR = "./input/real-plates/"
TEST_DATA_DIR = "./input/real-plates-for-test/"
MODEL_SAVE_DIR = './'
BATCH_SIZE = 8
IMAGE_WIDTH = 300
IMAGE_HEIGHT = 75
NUM_WORKERS = 1
EPOCHS = 200
DEVICE = "cpu"
